# Generated by Django 4.1.2 on 2022-11-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_inventory_counter_party_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='type',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
