# Generated by Django 4.1.2 on 2022-11-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventory_price_alter_inventory_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='barcode',
            field=models.ImageField(null=True, upload_to='media/barcode'),
        ),
    ]
