# Generated by Django 4.1.2 on 2022-11-21 04:56

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_inventory_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='barcode',
            field=models.ImageField(null=True, upload_to=pathlib.PurePosixPath('/home/aviox/Desktop/developer/tech_maadhyam_demo/tech_maadhyam/media')),
        ),
    ]
