# Generated by Django 4.1.2 on 2022-11-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_inventory_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='barcode',
            field=models.ImageField(blank=True, default='', upload_to='barcode/'),
        ),
    ]
