# Generated by Django 4.1.2 on 2022-11-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_inventory_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='warehouse',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='barcode',
            field=models.ImageField(blank=True, upload_to='barcode/'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_or_service',
            field=models.CharField(choices=[('Product', 'Product'), ('Service', 'Service')], default='Product', max_length=200),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='type',
            field=models.CharField(choices=[('Sell', 'Sell'), ('Buy', 'Buy'), ('Both', 'Both')], default='Sell', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='unit_of_measurement',
            field=models.CharField(choices=[('Kg', 'Kg'), ('M', 'M')], default='Kg', max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('warehouse', models.ManyToManyField(to='inventory.warehouse')),
            ],
        ),
    ]
