# Generated by Django 4.1.2 on 2022-11-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_warehouse_category_description_inventory_warehouse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rack',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='rack',
            field=models.ManyToManyField(to='inventory.rack'),
        ),
    ]
