# Generated by Django 4.1.2 on 2022-11-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_remove_rack_warehouse_warehouse_rack'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='racks',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
