# Generated by Django 4.1.3 on 2022-12-02 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_inventory_racks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='rack',
        ),
        migrations.AddField(
            model_name='rack',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
        ),
    ]
